export interface Participant {
  id: string; // Participant registration ID (e.g. "p_...")
  personId?: string | null; // Primary technical ID linking to Person.id
  displayId?: string | null; // Human-readable identifier (e.g. "Oliver_1")
  firstName: string;
  registeredAt: string;
  userId?: string;
}

export type MatchStatus = 'not_ready' | 'ready' | 'in_progress' | 'completed' | 'walkover';

export type TargetPoints = 6 | 7 | 11 | 21;
export type WinMargin = 1 | 2;
export type NumberOfSets = 1 | 3;
export type TournamentStage = 'regular' | 'semifinal' | 'final';

export interface StageFormatConfig {
  sets: NumberOfSets;         // 1 eller 3 sett
  targetPoints: TargetPoints; // 6, 7, 11 eller 21
  winMargin: WinMargin;       // 1 eller 2
}

export interface TournamentFormatSettings {
  regular: StageFormatConfig;   // Vanlige cuprunder
  semifinal: StageFormatConfig; // Semifinaler
  final: StageFormatConfig;     // Finale
}

export interface MatchSetScore {
  setNumber: number; // 1, 2 eller 3
  scoreA: number;
  scoreB: number;
}

export interface Match {
  id: string;
  round: number; // 1, 2, 3 ... final
  roundName: string; // e.g. "Runde 1", "Kvartfinale", "Semifinale", "Finale"
  stage?: TournamentStage; // 'regular' | 'semifinal' | 'final'
  position: number; // 0, 1, 2...
  playerA: Participant | null;
  playerB: Participant | null;
  winnerId: string | null;
  scoreA: number | null;
  scoreB: number | null;
  format?: StageFormatConfig;
  sets?: MatchSetScore[];
  setsWonA?: number | null;
  setsWonB?: number | null;
  tableNumber: 1 | 2 | null;
  status: MatchStatus;
  isWalkover: boolean;
  walkoverPlayerId?: string | null;
  nextMatchId: string | null;
  nextMatchSlot: 'A' | 'B' | null;
  startedAt?: string | null;
  completedAt?: string | null;
}

export interface Tournament {
  id: string;
  status: 'registration' | 'active' | 'completed';
  startedAt: string | null;
  completedAt: string | null;
  participants: Participant[];
  matches: Match[];
  winner: Participant | null;
  estimatedMinutesPerMatch: number; // default 10 min
  /** Fast bracket-størrelse: 16 (standard), 32 eller 64 spillere. */
  bracketCapacity?: 4 | 8 | 16 | 32 | 64;
  formatSettings?: TournamentFormatSettings;
}

export interface AlphaInterest {
  id: string;
  firstName: string;
  phone?: string;
  registeredAt: string;
  notes?: string;
  userId?: string;
  personId?: string;
}

export interface Person {
  id: string; // Random UUID (e.g. "550e8400-e29b-41d4-a716-446655440000")
  firstName: string; // Display name
  nameNumber: number; // Persistent sequential number for this firstName (1, 2, 3...)
  displayId: string; // Human-readable label (e.g. "Oliver_1", "Oliver_2")
  anonymousToken: string; // Technical random token
  createdAt: string;
  updatedAt: string;
  isSimulated?: boolean; // True if generated by tournament simulation, can be cleaned by RESET TESTDATA
}

export interface UserProfile {
  userId: string;
  firstName: string | null;
}

export interface UserActivityStatus {
  userId: string;
  firstName: string | null;
  tableTennis: {
    isRegistered: boolean;
    participant: Participant | null;
  };
  popcorn: {
    bong: PopcornBong | null;
  };
  alpha: {
    isInterested: boolean;
    interest: AlphaInterest | null;
  };
}

export interface Activity {
  id: string;
  name: string;
  shortDesc: string;
  fullDesc: string;
  iconName: string;
  time: string;
  location: string;
  enabled: boolean;
  badge?: string;
  highlight?: boolean;
}

export type BongStatus = 'blank' | 'activated' | 'used';

export interface PopcornBong {
  number: number;
  status: BongStatus;
  activatedAt?: string | null;
  usedAt?: string | null;
  personId?: string | null; // Primary technical ID linking to Person.id
  /** @deprecated Kept for display/legacy fallback. Use personId as primary technical identity. */
  userName?: string | null;
  /** @deprecated Kept for legacy client identification. */
  clientToken?: string | null;
}

export interface PopcornData {
  totalCapacity: number;
  bongs: PopcornBong[];
}

export interface KioskItem {
  id: string;
  name: string;
  desc?: string;
  price: number; // Strictly numeric price in NOK (e.g. 25, 0)
  icon: string;
  isAvailable?: boolean;
  category?: string;
  allowsFreeBong?: boolean;
  createdAt?: string;
}

export interface KioskSettings {
  vippsNumber?: string;
  vippsName?: string;
  vippsUrl?: string; // Optional official Vipps deep link / QR link (e.g. https://qr.vipps.no/28/...)
}

export interface PushSubscriptionTopic {
  active: boolean;
  expiresAt?: string | null;
  courseId?: string | null;
}

export interface PushSubscriptionRecord {
  id: string; // Hash of endpoint URL
  personId: string;
  endpoint: string;
  keys: {
    p256dh: string;
    auth: string;
  };
  topics: {
    tournament?: PushSubscriptionTopic;
    alphaCourse?: PushSubscriptionTopic;
  };
  userAgent?: string;
  createdAt: string;
  updatedAt: string;
  lastUsedAt?: string;
}

export interface AppState {
  event: {
    name: string;
    date: string;
    time: string;
    location: string;
    organizers: string[];
    freePopcornLimit: number;
    popcornClaimedCount: number;
  };
  popcorn: PopcornData;
  kioskItems?: KioskItem[];
  kioskSettings?: KioskSettings;
  activities: Activity[];
  tournament: Tournament;
  alphaInterests: AlphaInterest[];
  persons: Person[];
  updatedAt?: string;
}
